"""DomainSkillPublisher — render AWC insights as browser-harness domain-skills.

**Strategic role**: This is the reverse adapter that lets AWC contribute to
browser-harness's `agent-workspace/domain-skills/` ecosystem. Every BH
domain-skill is a Markdown file documenting a site's APIs, selectors,
URL patterns, and gotchas. AWC's :class:`SiteMemory`,
:class:`APISynthesizer`, and :class:`ActionGraphBuilder` already extract that
information — this publisher just renders it in BH's conventional layout so
it can be dropped into a PR against ``browser-use/browser-harness``.

The output follows the same section structure as the best-maintained BH
skills (see ``browser-harness/agent-workspace/domain-skills/github/``):

    # <domain> — <task>
    <preamble>

    ## Do this first
    <preferred APIs, read-only, high-confidence>

    ## Stable selectors
    <main content selector + noise selectors>

    ## URL patterns
    <entry points / hub pages from SiteMemory>

    ## Common workflows
    <per-action examples>

    ## Gotchas
    <quality warnings aggregated across the observed pages>

    <!-- Auto-generated by agent-web-compiler vX.Y.Z -->

Design constraints (mirroring :doc:`/docs/integration-with-browser-harness`):

1. **No secrets**. We scrub cookies, auth tokens, and user-specific query
   params before emitting. BH's skills are public.
2. **No user data**. Only structural / semantic information makes it in —
   never the actual content of a page the user compiled.
3. **Stable output**. Given identical inputs, we produce byte-identical
   Markdown. This matters for PR reviewers comparing diffs across versions.
4. **No file I/O in :meth:`generate`**. The method returns a string; only
   :meth:`write_to_repo` touches disk.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from agent_web_compiler import __version__ as awc_version
from agent_web_compiler.actiongraph.models import APICandidate

if TYPE_CHECKING:  # pragma: no cover
    from agent_web_compiler.actiongraph.models import ActionGraphModel
    from agent_web_compiler.core.document import AgentDocument
    from agent_web_compiler.memory.site_memory import SiteInsight


# Headers to always strip from ``APICandidate.headers_pattern`` before publishing.
# These are the typical leaks: auth tokens, session cookies, CSRF headers, and
# any ``x-*`` custom headers that often carry user ids.
_SECRET_HEADER_PATTERNS = (
    re.compile(r"^authorization$", re.IGNORECASE),
    re.compile(r"^cookie$", re.IGNORECASE),
    re.compile(r"^x-csrf", re.IGNORECASE),
    re.compile(r"^x-auth", re.IGNORECASE),
    re.compile(r"^x-api-key$", re.IGNORECASE),
    re.compile(r"^x-session", re.IGNORECASE),
    re.compile(r"^x-user", re.IGNORECASE),
)

# Query-param keys to redact.
_SECRET_QUERY_PARAMS = frozenset({
    "token", "access_token", "id_token", "api_key", "apikey", "session",
    "sessionid", "sid", "auth", "password", "secret",
})


def _redact_headers(headers: dict[str, str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for k, v in (headers or {}).items():
        if any(p.match(k) for p in _SECRET_HEADER_PATTERNS):
            out[k] = "<redacted>"
        else:
            out[k] = v
    return out


def _redact_endpoint(endpoint: str) -> str:
    """Strip secret query parameters from an endpoint URL.

    We don't import urllib here because the point isn't to *correctly* parse
    every URL — it's to ensure no obvious secrets leak into the Markdown.
    For anything that doesn't round-trip cleanly through this function, the
    publisher conservatively drops the whole query string.
    """
    if "?" not in endpoint:
        return endpoint
    base, _, qs = endpoint.partition("?")
    parts = qs.split("&")
    kept: list[str] = []
    for part in parts:
        if "=" not in part:
            kept.append(part)
            continue
        key, _, _ = part.partition("=")
        if key.lower() in _SECRET_QUERY_PARAMS:
            kept.append(f"{key}=<redacted>")
        else:
            kept.append(part)
    return f"{base}?{'&'.join(kept)}" if kept else base


# ---------------------------------------------------------------------------
# Public result object
# ---------------------------------------------------------------------------


@dataclass
class DomainSkill:
    """A rendered BH-compatible domain-skill Markdown document."""

    domain: str
    task: str
    markdown: str
    # Metadata carried alongside the text for use by test suites / CI, not
    # embedded in the markdown itself.
    api_count: int = 0
    selector_count: int = 0
    generated_at: float = field(default_factory=time.time)

    def filename(self) -> str:
        """Filename inside ``agent-workspace/domain-skills/<site>/<task>.md``."""
        # BH's tree uses lowercase, hyphen-separated task names.
        return f"{self.task}.md"

    def site_dir(self, bh_repo_root: str | Path) -> Path:
        """Directory path inside the BH repo this skill belongs to."""
        return Path(bh_repo_root) / "agent-workspace" / "domain-skills" / self._slug()

    def write_to_repo(self, bh_repo_root: str | Path, *, overwrite: bool = False) -> Path:
        """Write the markdown to ``agent-workspace/domain-skills/<slug>/<task>.md``.

        Raises:
            FileExistsError: If the target file exists and ``overwrite`` is False.
        """
        target = self.site_dir(bh_repo_root) / self.filename()
        if target.exists() and not overwrite:
            raise FileExistsError(
                f"{target} already exists. Pass overwrite=True to replace."
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.markdown, encoding="utf-8")
        return target

    def _slug(self) -> str:
        """Convert domain to BH's ``<site>`` slug.

        Rules (observed from BH's repo):
        - strip ``www.`` and TLD
        - replace dots with hyphens (``stack.overflow.com`` → ``stack-overflow``)
        - lowercase
        """
        d = self.domain.lower().removeprefix("www.")
        # take everything before the last dot (chop off TLD)
        if "." in d:
            d = d.rsplit(".", 1)[0]
        return d.replace(".", "-").replace("_", "-")


# ---------------------------------------------------------------------------
# Publisher
# ---------------------------------------------------------------------------


class DomainSkillPublisher:
    """Render an :class:`AgentDocument` (+ optional :class:`SiteInsight`) as a
    browser-harness domain-skill.

    Two entry points:

    - :meth:`generate_from_document` — single page. Pulls APIs from
      :class:`APISynthesizer`, selectors from the action list.
    - :meth:`generate_from_site` — multi-page. Adds URL patterns, common
      actions, and login/download flags from :class:`SiteMemory`.

    Both return a :class:`DomainSkill`. Use ``.write_to_repo(bh_repo_root)``
    to drop the file into a local clone of ``browser-use/browser-harness``.
    """

    # Cap list lengths to keep generated skills readable. Real BH skills are
    # rarely longer than ~200 lines; long auto-generated dumps don't get
    # reviewed.
    MAX_APIS = 8
    MAX_NOISE_SELECTORS = 8
    MAX_ENTRY_POINTS = 6
    MAX_COMMON_ACTIONS = 6
    MAX_GOTCHAS = 6

    # ------------------------------------------------------------------
    # Entry points
    # ------------------------------------------------------------------

    def generate_from_document(
        self,
        doc: AgentDocument,
        *,
        task: str = "scraping",
        api_candidates: list[APICandidate] | None = None,
    ) -> DomainSkill:
        """Render a single-page skill.

        Args:
            doc: The compiled :class:`AgentDocument`.
            task: BH skill filename stem. Conventionally ``"scraping"`` for
                read-only data tasks, ``"upload"`` / ``"repo-actions"`` for
                specific flows.
            api_candidates: Pre-computed APIs. If omitted, synthesizes from
                the document on the fly.
        """
        if api_candidates is None:
            from agent_web_compiler.actiongraph.api_synthesizer import APISynthesizer

            api_candidates = APISynthesizer().synthesize_from_document(doc)

        domain = self._domain_from_url(doc.source_url or "")
        md = self._render(
            domain=domain,
            task=task,
            preamble=self._preamble_from_doc(doc, api_candidates),
            apis=api_candidates,
            main_selector=self._main_content_selector(doc),
            noise_selectors=[],
            entry_points=[doc.source_url] if doc.source_url else [],
            common_actions=[],
            gotchas=list(doc.quality.warnings),
        )
        return DomainSkill(
            domain=domain,
            task=task,
            markdown=md,
            api_count=len(api_candidates),
            selector_count=sum(1 for a in doc.actions if a.selector),
        )

    def generate_from_site(
        self,
        insight: SiteInsight,
        *,
        task: str = "scraping",
        api_candidates: list[APICandidate] | None = None,
        action_graph: ActionGraphModel | None = None,
        extra_gotchas: list[str] | None = None,
    ) -> DomainSkill:
        """Render a multi-page skill backed by :class:`SiteMemory`.

        Args:
            insight: A :class:`SiteInsight` produced after observing 3+ pages
                of the site.
            task: BH skill filename stem.
            api_candidates: Merged list of APIs across the site. Optional.
            action_graph: Optional multi-page :class:`ActionGraphModel`. Used
                today only for gotchas/metadata; future versions can surface
                navigation paths.
            extra_gotchas: Manually-authored gotchas to append (e.g. "R@5
                evaluation flagged these items as low-confidence").
        """
        apis = api_candidates or []

        # Login-required is a gotcha unique to BH-published skills.
        auto_gotchas: list[str] = []
        if insight.login_required:
            auto_gotchas.append(
                "Login required — most entry points redirect to an auth page "
                "when accessed without session cookies. Use BH with the user's "
                "real Chrome (`BU_NAME` session) so cookies are present."
            )
        if insight.pages_observed > 0 and insight.avg_blocks_per_page < 5:
            auto_gotchas.append(
                f"Low content density observed ({insight.avg_blocks_per_page:.1f} "
                "blocks/page avg) — the site likely renders content client-side "
                "after `readyState==complete`; add an extra `wait(2)`."
            )
        gotchas = auto_gotchas + list(extra_gotchas or [])

        md = self._render(
            domain=insight.domain,
            task=task,
            preamble=self._preamble_from_insight(insight, apis),
            apis=apis,
            main_selector=insight.main_content_selector,
            noise_selectors=list(insight.noise_selectors),
            entry_points=list(insight.entry_points),
            common_actions=list(insight.common_actions),
            gotchas=gotchas,
        )
        return DomainSkill(
            domain=insight.domain,
            task=task,
            markdown=md,
            api_count=len(apis),
            selector_count=1 + len(insight.noise_selectors),
        )

    # ------------------------------------------------------------------
    # Rendering core
    # ------------------------------------------------------------------

    def _render(
        self,
        *,
        domain: str,
        task: str,
        preamble: str,
        apis: list[APICandidate],
        main_selector: str | None,
        noise_selectors: list[str],
        entry_points: list[str],
        common_actions: list[dict],
        gotchas: list[str],
    ) -> str:
        lines: list[str] = []
        title = task.replace("-", " ").replace("_", " ").title()
        lines.append(f"# {domain} — {title}")
        lines.append("")
        lines.append(preamble)
        lines.append("")

        # --- Do this first: APIs --------------------------------------
        safe_apis = [
            a for a in apis
            if a.safety_level == "read_only" and a.confidence >= 0.5
        ][: self.MAX_APIS]
        if safe_apis:
            lines.append("## Do this first")
            lines.append("")
            lines.append(
                "**Prefer these endpoints discovered by agent-web-compiler — "
                "no browser needed.**"
            )
            lines.append("")
            lines.append("```python")
            lines.append("import json")
            for api in safe_apis:
                endpoint = _redact_endpoint(api.endpoint)
                headers = _redact_headers(api.headers_pattern or {})
                desc = api.description or api.derived_from_action_id or api.api_id
                lines.append(f"# {desc} (confidence={api.confidence:.2f})")
                if headers:
                    lines.append(f"headers = {headers!r}")
                    lines.append(f"data = json.loads(http_get({endpoint!r}, headers=headers))")
                else:
                    lines.append(f"data = json.loads(http_get({endpoint!r}))")
            lines.append("```")
            lines.append("")

        # --- Stable selectors ----------------------------------------
        sel_section: list[str] = []
        if main_selector:
            sel_section.append(f"- **main content**: `{main_selector}`")
        if noise_selectors:
            for s in noise_selectors[: self.MAX_NOISE_SELECTORS]:
                sel_section.append(f"- noise / skip: `{s}`")
        if sel_section:
            lines.append("## Stable selectors")
            lines.append("")
            lines.extend(sel_section)
            lines.append("")

        # --- URL patterns --------------------------------------------
        if entry_points:
            lines.append("## URL patterns")
            lines.append("")
            for ep in entry_points[: self.MAX_ENTRY_POINTS]:
                lines.append(f"- `{_redact_endpoint(ep)}`")
            lines.append("")

        # --- Common workflows ----------------------------------------
        if common_actions:
            lines.append("## Common workflows")
            lines.append("")
            for ca in common_actions[: self.MAX_COMMON_ACTIONS]:
                role = ca.get("role", "action")
                freq = ca.get("frequency")
                suffix = f" — frequency {freq:.0%}" if isinstance(freq, (int, float)) else ""
                lines.append(f"- **{role}**{suffix}")
            lines.append("")

        # --- Gotchas --------------------------------------------------
        if gotchas:
            lines.append("## Gotchas")
            lines.append("")
            for g in gotchas[: self.MAX_GOTCHAS]:
                lines.append(f"- {g}")
            lines.append("")

        # --- Provenance footer ---------------------------------------
        lines.append(
            f"<!-- Auto-generated by agent-web-compiler v{awc_version}. "
            "Edit freely — subsequent regenerations preserve manual changes "
            "only if you move them outside the section headers above. -->"
        )
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Preamble helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _preamble_from_doc(
        doc: AgentDocument, apis: list[APICandidate]
    ) -> str:
        host = DomainSkillPublisher._domain_from_url(doc.source_url or "")
        n_blocks = doc.block_count
        n_actions = doc.action_count
        api_note = (
            f"{len(apis)} candidate API(s) detected"
            if apis
            else "no API candidates found — browser path required"
        )
        return (
            f"`https://{host}` — one page compiled "
            f"({n_blocks} blocks, {n_actions} actions). {api_note}."
        )

    @staticmethod
    def _preamble_from_insight(
        insight: SiteInsight, apis: list[APICandidate]
    ) -> str:
        auth_note = "auth required" if insight.login_required else "public"
        api_note = (
            f"{len(apis)} candidate API(s) across the site"
            if apis
            else "no API candidates found — browser path required"
        )
        return (
            f"`https://{insight.domain}` — "
            f"{insight.pages_observed} page(s) observed ({auth_note}). {api_note}."
        )

    @staticmethod
    def _main_content_selector(doc: AgentDocument) -> str | None:
        """Pick the 'main content' selector for a single-page skill.

        Heuristic: look at the action with the highest priority; if it has a
        CSS selector, return the structural ancestor hint ``main``/``article``
        if the selector points inside one, else the selector itself. Kept
        deliberately simple — SiteInsight-based rendering has better data.
        """
        if not doc.actions:
            return None
        sel = max(doc.actions, key=lambda a: a.priority).selector
        if not sel:
            return None
        # Only return the selector if it contains a structural tag — otherwise
        # "a.primary" is usually not a great "main content" hint.
        if any(tag in sel for tag in ("main", "article", "#content", ".content")):
            return sel
        return None

    @staticmethod
    def _domain_from_url(url: str) -> str:
        from urllib.parse import urlparse

        parsed = urlparse(url)
        return parsed.netloc or parsed.path.split("/", 1)[0] or "unknown-host"
