"""Tests for DomainSkillPublisher — BH-compatible skill rendering."""

from __future__ import annotations

from pathlib import Path

import pytest

from agent_web_compiler.actiongraph.models import APICandidate
from agent_web_compiler.core.action import Action, ActionType
from agent_web_compiler.core.document import AgentDocument, Quality, SourceType
from agent_web_compiler.memory.site_memory import SiteInsight
from agent_web_compiler.publisher import DomainSkill, DomainSkillPublisher


def _make_doc(
    url: str = "https://github.com/browser-use/browser-harness",
    actions: list[Action] | None = None,
    warnings: list[str] | None = None,
) -> AgentDocument:
    return AgentDocument(
        doc_id="doc_t",
        source_type=SourceType.HTML,
        source_url=url,
        title="Test",
        blocks=[],
        actions=actions or [],
        quality=Quality(warnings=warnings or []),
    )


# ---------------------------------------------------------------------------
# Single-page rendering
# ---------------------------------------------------------------------------


def test_generate_from_document_includes_title_and_preamble() -> None:
    doc = _make_doc()
    skill = DomainSkillPublisher().generate_from_document(doc, task="scraping")

    assert isinstance(skill, DomainSkill)
    assert skill.domain == "github.com"
    assert skill.task == "scraping"

    md = skill.markdown
    assert md.startswith("# github.com — Scraping")
    assert "one page compiled" in md
    assert "Auto-generated by agent-web-compiler" in md


def test_generate_from_document_renders_api_section() -> None:
    doc = _make_doc()
    apis = [
        APICandidate(
            api_id="api1",
            derived_from_action_id="a1",
            endpoint="https://api.github.com/repos/x/y",
            method="GET",
            confidence=0.9,
            safety_level="read_only",
            description="Repo metadata",
        ),
        APICandidate(
            api_id="api2",
            endpoint="https://api.github.com/write-op",
            method="POST",
            confidence=0.9,
            safety_level="write",  # must be filtered out
        ),
    ]
    skill = DomainSkillPublisher().generate_from_document(
        doc, api_candidates=apis, task="scraping"
    )
    md = skill.markdown
    assert "## Do this first" in md
    assert "api.github.com/repos/x/y" in md
    assert "write-op" not in md  # write APIs are not auto-published


def test_api_section_redacts_secret_headers_and_tokens() -> None:
    doc = _make_doc()
    apis = [
        APICandidate(
            api_id="api_with_secret",
            endpoint="https://api.example.com/me?token=SUPER-SECRET&page=1",
            method="GET",
            confidence=0.9,
            safety_level="read_only",
            headers_pattern={"Authorization": "Bearer eyJleak", "X-Public": "v1"},
        ),
    ]
    skill = DomainSkillPublisher().generate_from_document(doc, api_candidates=apis)
    md = skill.markdown
    assert "SUPER-SECRET" not in md
    assert "eyJleak" not in md
    assert "<redacted>" in md
    assert "X-Public" in md  # safe headers are kept
    assert "page=1" in md


def test_gotchas_rendered_from_quality_warnings() -> None:
    doc = _make_doc(warnings=["parse_confidence below threshold"])
    skill = DomainSkillPublisher().generate_from_document(doc)
    assert "## Gotchas" in skill.markdown
    assert "parse_confidence" in skill.markdown


def test_main_content_selector_respected_when_structural() -> None:
    # An action whose selector points inside a <main> tag should become the
    # skill's main-content selector.
    doc = _make_doc(
        actions=[
            Action(
                id="a_hi",
                type=ActionType.CLICK,
                label="Hi",
                selector="main#content .item",
                priority=0.9,
            )
        ]
    )
    skill = DomainSkillPublisher().generate_from_document(doc)
    assert "## Stable selectors" in skill.markdown
    assert "main#content .item" in skill.markdown


def test_non_structural_selector_is_not_promoted_to_main_content() -> None:
    doc = _make_doc(
        actions=[
            Action(
                id="a_btn",
                type=ActionType.CLICK,
                label="Sign in",
                selector="button.primary",
                priority=0.9,
            )
        ]
    )
    skill = DomainSkillPublisher().generate_from_document(doc)
    # A bare selector like "button.primary" doesn't qualify as a "main
    # content" hint — we don't want misleading skills.
    assert "## Stable selectors" not in skill.markdown


# ---------------------------------------------------------------------------
# Multi-page rendering via SiteInsight
# ---------------------------------------------------------------------------


def test_generate_from_site_auth_gotcha() -> None:
    insight = SiteInsight(
        domain="app.example.com",
        pages_observed=5,
        avg_blocks_per_page=20.0,
        login_required=True,
        entry_points=["https://app.example.com/", "https://app.example.com/inbox"],
        noise_selectors=["footer", "aside.ads"],
        main_content_selector="main#root",
        common_actions=[{"role": "search", "frequency": 0.8}],
    )
    skill = DomainSkillPublisher().generate_from_site(insight)
    md = skill.markdown

    assert "# app.example.com — Scraping" in md
    assert "auth required" in md
    assert "Login required" in md  # auto-gotcha for login-walled sites
    assert "main#root" in md
    assert "footer" in md
    assert "`https://app.example.com/`" in md
    assert "- **search**" in md


def test_generate_from_site_low_density_gotcha() -> None:
    insight = SiteInsight(
        domain="spa.example.com",
        pages_observed=3,
        avg_blocks_per_page=2.0,  # low → SPA hydration gotcha
    )
    skill = DomainSkillPublisher().generate_from_site(insight)
    assert "wait(2)" in skill.markdown


# ---------------------------------------------------------------------------
# Filesystem surface
# ---------------------------------------------------------------------------


def test_write_to_repo_creates_dirs_and_writes_file(tmp_path: Path) -> None:
    doc = _make_doc(url="https://stackoverflow.com/questions/42")
    skill = DomainSkillPublisher().generate_from_document(doc, task="scraping")
    target = skill.write_to_repo(tmp_path)

    assert target.exists()
    assert target.name == "scraping.md"
    assert target.parent.name == "stackoverflow"
    assert target.read_text().startswith("# stackoverflow.com — Scraping")


def test_write_to_repo_refuses_existing_without_overwrite(tmp_path: Path) -> None:
    doc = _make_doc(url="https://github.com/x/y")
    skill = DomainSkillPublisher().generate_from_document(doc)
    skill.write_to_repo(tmp_path)

    with pytest.raises(FileExistsError):
        skill.write_to_repo(tmp_path)

    # overwrite=True should succeed
    skill.write_to_repo(tmp_path, overwrite=True)


def test_slug_handles_www_and_subdomains() -> None:
    for (domain, expected) in [
        ("www.github.com", "github"),
        ("stack.overflow.com", "stack-overflow"),
        ("example.org", "example"),
        ("single", "single"),
    ]:
        sk = DomainSkill(domain=domain, task="scraping", markdown="")
        assert sk._slug() == expected  # noqa: SLF001


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------


def test_generate_is_deterministic_for_identical_inputs() -> None:
    doc = _make_doc()
    apis = [
        APICandidate(
            api_id="api1",
            endpoint="https://api.github.com/x",
            method="GET",
            confidence=0.9,
            safety_level="read_only",
        ),
    ]
    s1 = DomainSkillPublisher().generate_from_document(doc, api_candidates=apis)
    s2 = DomainSkillPublisher().generate_from_document(doc, api_candidates=apis)
    assert s1.markdown == s2.markdown
